<style>
	.animation-list .col-md-4 {
		min-height: 80px;
		padding-bottom: 10px;
	}
	.animation-list img {
		align-content: center;
		font-size: 30pt;
		line-height: 30pt !important;
		height: 80px;
	}
	.animation-list span {
		display: block;
		padding-top: 5px;
	}
</style>
<h1>Animates</h1>
<div class="animation-list row">
	<div class="col-md-4"><img src="img/logo.svg" class="text-center img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:bounceflash;animation-iteration-count: infinite;"><span>bounceflash</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:pulse;animation-iteration-count: infinite;"><span>pulse</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rubberBand;animation-iteration-count: infinite;"><span>rubberBand</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:shake;animation-iteration-count: infinite;"><span>shake</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:headShake;animation-iteration-count: infinite;"><span>headShake</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:swing;animation-iteration-count: infinite;"><span>swing</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:tada;animation-iteration-count: infinite;"><span>tada</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:wobble;animation-iteration-count: infinite;"><span>wobble</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:jello;animation-iteration-count: infinite;"><span>jello</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:bounceIn;animation-iteration-count: infinite;"><span>bounceIn</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:bounceInDown;animation-iteration-count: infinite;"><span>bounceInDown</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:bounceInLeft;animation-iteration-count: infinite;"><span>bounceInLeft</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:bounceInRight;animation-iteration-count: infinite;"><span>bounceInRight</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:bounceInUp;animation-iteration-count: infinite;"><span>bounceInUp</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:bounceOut;animation-iteration-count: infinite;"><span>bounceOut</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:bounceOutDown;animation-iteration-count: infinite;"><span>bounceOutDown</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:bounceOutLeft;animation-iteration-count: infinite;"><span>bounceOutLeft</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:bounceOutRight;animation-iteration-count: infinite;"><span>bounceOutRight</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:bounceOutUp;animation-iteration-count: infinite;"><span>bounceOutUp</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeIn;animation-iteration-count: infinite;"><span>fadeIn</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeInDown;animation-iteration-count: infinite;"><span>fadeInDown</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeInDownBig;animation-iteration-count: infinite;"><span>fadeInDownBig</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeInLeft;animation-iteration-count: infinite;"><span>fadeInLeft</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeInLeftBig;animation-iteration-count: infinite;"><span>fadeInLeftBig</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeInRight;animation-iteration-count: infinite;"><span>fadeInRight</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeInRightBig;animation-iteration-count: infinite;"><span>fadeInRightBig</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeInUp;animation-iteration-count: infinite;"><span>fadeInUp</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeInUpBig;animation-iteration-count: infinite;"><span>fadeInUpBig</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeOut;animation-iteration-count: infinite;"><span>fadeOut</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeOutDown;animation-iteration-count: infinite;"><span>fadeOutDown</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeOutDownBig;animation-iteration-count: infinite;"><span>fadeOutDownBig</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeOutLeft;animation-iteration-count: infinite;"><span>fadeOutLeft</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeOutLeftBig;animation-iteration-count: infinite;"><span>fadeOutLeftBig</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeOutRight;animation-iteration-count: infinite;"><span>fadeOutRight</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeOutRightBig;animation-iteration-count: infinite;"><span>fadeOutRightBig</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeOutUp;animation-iteration-count: infinite;"><span>fadeOutUp</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:fadeOutUpBig;animation-iteration-count: infinite;"><span>fadeOutUpBig</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:flip;animation-iteration-count: infinite;"><span>flip</span></div>
	<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:flipInX;animation-iteration-count: infinite;"><span>flipInX</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:flipInY;animation-iteration-count: infinite;"><span>flipInY</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:flipOutX;animation-iteration-count: infinite;"><span>flipOutX</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:flipOutY;animation-iteration-count: infinite;"><span>flipOutY</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:lightSpeedIn;animation-iteration-count: infinite;"><span>lightSpeedIn</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:lightSpeedOut;animation-iteration-count: infinite;"><span>lightSpeedOut</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rotateIn;animation-iteration-count: infinite;"><span>rotateIn</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rotateInDownLeft;animation-iteration-count: infinite;"><span>rotateInDownLeft</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rotateInDownRight;animation-iteration-count: infinite;"><span>rotateInDownRight</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rotateInUpLeft;animation-iteration-count: infinite;"><span>rotateInUpLeft</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rotateInUpRight;animation-iteration-count: infinite;"><span>rotateInUpRight</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rotateOut;animation-iteration-count: infinite;"><span>rotateOut</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rotateOutDownLeft;animation-iteration-count: infinite;"><span>rotateOutDownLeft</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rotateOutDownRight;animation-iteration-count: infinite;"><span>rotateOutDownRight</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rotateOutUpLeft;animation-iteration-count: infinite;"><span>rotateOutUpLeft</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rotateOutUpRight;animation-iteration-count: infinite;"><span>rotateOutUpRight</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:hinge;animation-iteration-count: infinite;"><span>hinge</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rollIn;animation-iteration-count: infinite;"><span>rollIn</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:rollOut;animation-iteration-count: infinite;"><span>rollOut</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:zoomIn;animation-iteration-count: infinite;"><span>zoomIn</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:zoomInDown;animation-iteration-count: infinite;"><span>zoomInDown</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:zoomInLeft;animation-iteration-count: infinite;"><span>zoomInLeft</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:zoomInRight;animation-iteration-count: infinite;"><span>zoomInRight</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:zoomInUp;animation-iteration-count: infinite;"><span>zoomInUp</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:zoomOut;animation-iteration-count: infinite;"><span>zoomOut</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:zoomOutDown;animation-iteration-count: infinite;"><span>zoomOutDown</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:zoomOutLeft;animation-iteration-count: infinite;"><span>zoomOutLeft</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:zoomOutRight;animation-iteration-count: infinite;"><span>zoomOutRight</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:zoomOutUp;animation-iteration-count: infinite;"><span>zoomOutUp</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:slideInDown;animation-iteration-count: infinite;"><span>slideInDown</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:slideInLeft;animation-iteration-count: infinite;"><span>slideInLeft</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:slideInRight;animation-iteration-count: infinite;"><span>slideInRight</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:slideInUp;animation-iteration-count: infinite;"><span> slideInUp </span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:slideOutDown;animation-iteration-count: infinite;"><span>slideOutDown</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:slideOutLeft;animation-iteration-count: infinite;"><span>slideOutLeft</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:slideOutRight;animation-iteration-count: infinite;"><span>slideOutRight</span></div>
<div class="col-md-4"><img src="img/logo.svg" class="img-responsive" style="opacity: 1;animation-fill-mode: both;animation-duration: 1.2s;animation-delay: 0s;animation-name:slideOutUp;animation-iteration-count: infinite;"><span>slideOutUp<span></span></div>
</div>